### ISSUE TITLE
Error when using transfromImage

### ISSUE THREAD

**Issue by zmiller22** [saalfeldlab/template-building#13]
I am having problems using the transformImage command, but can't quite figure out what the error message means. I am trying to apply a transform from a BigWarp landmarks.csv file using the following command, and getting the following error message. On thing I was thinking is perhaps I have missed a step in my set up, but I installed Maven and jgo and have tested both. I would go look in the code myself, but I am not really sure where jgo is linking to...

```
./transformImage \
-i  \
/mnt/c/Users/TracingPC1/Desktop/BIGWARP/VOLUMES/isotropic_stitched_ch01_rotate90_flipZ_flipV.nii \
-o  \
/mnt/c/Users/TracingPC1/Desktop/BIGWARP/TRANSFORMS/190529_Transforms/isotropic_stitched_ch01_rotate90_flipZ_flipV_antsTest.nii \
-t \
/mnt/c/Users/TracingPC1/Desktop/BIGWARP/TRANSFORMS/190529_Transforms/landmarks.csv \
-j 4                                                                                
 ```
`
Exception in thread "main" picocli.CommandLine$ExecutionException: Error while calling command (process.TransformImage@32a068d1): java.lang.NullPointerException at picocli.CommandLine.execute(CommandLine.java:1068) at picocli.CommandLine.access$900(CommandLine.java:142) at picocli.CommandLine$RunLast.handle(CommandLine.java:1255) at picocli.CommandLine$RunLast.handle(CommandLine.java:1223) at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1131) at picocli.CommandLine.parseWithHandlers(CommandLine.java:1414) at picocli.CommandLine.call(CommandLine.java:1690) at picocli.CommandLine.call(CommandLine.java:1614) at process.TransformImage.main(TransformImage.java:89) Caused by: java.lang.NullPointerException at net.imglib2.realtransform.AbstractRealTransformSequence.add(AbstractRealTransformSequence.java:73) at org.janelia.saalfeldlab.transform.io.TransformReader.readTransforms(TransformReader.java:46) at process.TransformImage.setup(TransformImage.java:114) at process.TransformImage.call(TransformImage.java:134) at process.TransformImage.call(TransformImage.java:46) at picocli.CommandLine.execute(CommandLine.java:1061) ... 8 more`

**Comment by bogovicj** [comment]
@zmiller22 

Thanks for trying that out.  I'll have a look and have some answers next week (today is super busy)

**Comment by zmiller22** [comment]
```
tracingpc1@TracingPC1:~/template-building$ git describe --tags 
v0.1.0
tracingpc1@TracingPC1:~/template-building/jgo$ ./transformImage -v
0.0.2-SNAPSHOT                       
```

**Comment by bogovicj** [comment]
If you'd like, you could give the master branch a try while you're waiting on me

**Comment by zmiller22** [comment]
Thanks, I will check it out when I get a chance.

**Comment by bogovicj** [comment]
master branch seems better behaved for me, see my longer answer here:
https://forum.image.sc/t/exporting-transforms-from-bigwarp/27813/2?u=bogovicj
