### ISSUE TITLE
Array out of bound exception on example files

### ISSUE THREAD

**Issue by Nils-Reinhard** [saalfeldlab/template-building#20]
Hi;

I tried to run [the demo for transformImage](https://github.com/saalfeldlab/template-building/wiki/Usage-examples#transforming-images) and received the following stack trace:

```
transformImage -i FCWB_small.nrrd     -o fcwb-to-jrc18f.nrrd     -f JRC2018_FEMALE_small.nrrd     -t JRC2018F_FCWB_small.h5     -j 4
17:26:32.231 [main] DEBUG process.TransformImage - output resolution : [1.24296, 1.24296, 1.24296]
17:26:32.234 [main] DEBUG process.TransformImage - output size       : [0, 0, 0] -> [504, 234, 146], dimensions (505, 235, 147)
17:26:32.352 [main] INFO  process.TransformImage - allocating
17:26:32.358 [main] INFO  process.TransformImage - copying with 4 threads.
splitPoints[i]: 36
splitPoints[i]: 72
splitPoints[i]: 108
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: Index 15360 out of bounds for length 15360
        at net.imglib2.cache.util.CacheAsUncheckedCacheAdapter.get(CacheAsUncheckedCacheAdapter.java:32)
        at net.imglib2.img.cell.LazyCellImg$LazyCells.get(LazyCellImg.java:104)
        at net.imglib2.img.list.AbstractLongListImg$LongListRandomAccess.get(AbstractLongListImg.java:274)
        at net.imglib2.img.cell.CellRandomAccess.getCell(CellRandomAccess.java:136)
        at net.imglib2.img.cell.CellRandomAccess.updatePosition(CellRandomAccess.java:474)
        at net.imglib2.img.cell.CellRandomAccess.fwd(CellRandomAccess.java:164)
        at net.imglib2.view.FullSourceMapSlicingRandomAccess.fwd(FullSourceMapSlicingRandomAccess.java:183)
        at net.imglib2.converter.AbstractConvertedRandomAccess.fwd(AbstractConvertedRandomAccess.java:110)
        at net.imglib2.outofbounds.AbstractOutOfBoundsValue.fwd(AbstractOutOfBoundsValue.java:138)
        at net.imglib2.interpolation.randomaccess.NLinearInterpolator.graycodeFwdRecursive(NLinearInterpolator.java:227)
        at net.imglib2.interpolation.randomaccess.NLinearInterpolator.graycodeFwdRecursive(NLinearInterpolator.java:233)
        at net.imglib2.interpolation.randomaccess.NLinearInterpolator.graycodeFwdRecursive(NLinearInterpolator.java:233)
        at net.imglib2.interpolation.randomaccess.NLinearInterpolator.graycodeFwdRecursive(NLinearInterpolator.java:233)
        at net.imglib2.interpolation.randomaccess.NLinearInterpolator.get(NLinearInterpolator.java:205)
        at net.imglib2.interpolation.randomaccess.NLinearInterpolator.get(NLinearInterpolator.java:53)
        at net.imglib2.realtransform.RealTransformRealRandomAccessible$RealTransformRealRandomAccess.get(RealTransformRealRandomAccessible.java:97)
        at net.imglib2.realtransform.DeformationFieldTransform.apply(DeformationFieldTransform.java:124)
        at net.imglib2.realtransform.AbstractRealTransformSequence.apply(AbstractRealTransformSequence.java:156)
        at net.imglib2.realtransform.ExplicitInvertibleRealTransform.apply(ExplicitInvertibleRealTransform.java:68)
        at net.imglib2.realtransform.AbstractRealTransformSequence.apply(AbstractRealTransformSequence.java:163)
        at net.imglib2.realtransform.AbstractRealTransformSequence.apply(AbstractRealTransformSequence.java:160)
        at net.imglib2.realtransform.RealTransformRealRandomAccessible$RealTransformRealRandomAccess.apply(RealTransformRealRandomAccessible.java:90)
        at net.imglib2.realtransform.RealTransformRealRandomAccessible$RealTransformRealRandomAccess.get(RealTransformRealRandomAccessible.java:96)
        at net.imglib2.view.RandomAccessibleOnRealRandomAccessible$RandomAccessOnRealRandomAccessible.get(RandomAccessibleOnRealRandomAccessible.java:194)
        at util.RenderUtil$2.call(RenderUtil.java:226)
        at util.RenderUtil$2.call(RenderUtil.java:213)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: Index 15360 out of bounds for length 15360
        at net.imglib2.cache.ref.SoftRefLoaderCache.get(SoftRefLoaderCache.java:111)
        at net.imglib2.cache.util.LoaderCacheAsCacheAdapter.get(LoaderCacheAsCacheAdapter.java:30)
        at net.imglib2.cache.util.CacheAsUncheckedCacheAdapter.get(CacheAsUncheckedCacheAdapter.java:28)
        ... 29 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 15360 out of bounds for length 15360
        at net.imglib2.img.basictypeaccess.array.AbstractShortArray.getValue(AbstractShortArray.java:61)
        at net.imglib2.type.numeric.integer.GenericShortType.getShort(GenericShortType.java:131)
        at net.imglib2.type.numeric.integer.GenericShortType.set(GenericShortType.java:187)
        at net.imglib2.type.numeric.integer.GenericShortType.set(GenericShortType.java:53)
        at org.janelia.saalfeldlab.n5.imglib2.N5CellLoader.copyIntersection(N5CellLoader.java:328)
        at org.janelia.saalfeldlab.n5.imglib2.N5CellLoader.lambda$createCopy$2(N5CellLoader.java:205)
        at org.janelia.saalfeldlab.n5.imglib2.N5CellLoader.load(N5CellLoader.java:144)
        at net.imglib2.cache.img.LoadedCellCacheLoader.get(LoadedCellCacheLoader.java:91)
        at net.imglib2.cache.img.LoadedCellCacheLoader.get(LoadedCellCacheLoader.java:51)
        at net.imglib2.cache.ref.SoftRefLoaderCache.get(SoftRefLoaderCache.java:101)
        ... 31 more
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: Index 15360 out of bounds for length 15360
        at net.imglib2.cache.util.CacheAsUncheckedCacheAdapter.get(CacheAsUncheckedCacheAdapter.java:32)
        at net.imglib2.img.cell.LazyCellImg$LazyCells.get(LazyCellImg.java:104)
        at net.imglib2.img.list.AbstractLongListImg$LongListRandomAccess.get(AbstractLongListImg.java:274)
        at net.imglib2.img.cell.CellRandomAccess.getCell(CellRandomAccess.java:136)
        at net.imglib2.img.cell.CellRandomAccess.updatePosition(CellRandomAccess.java:474)
        at net.imglib2.img.cell.CellRandomAccess.fwd(CellRandomAccess.java:164)
        at net.imglib2.view.FullSourceMapSlicingRandomAccess.fwd(FullSourceMapSlicingRandomAccess.java:183)
        at net.imglib2.converter.AbstractConvertedRandomAccess.fwd(AbstractConvertedRandomAccess.java:110)
        at net.imglib2.outofbounds.AbstractOutOfBoundsValue.fwd(AbstractOutOfBoundsValue.java:138)
        at net.imglib2.interpolation.randomaccess.NLinearInterpolator.graycodeFwdRecursive(NLinearInterpolator.java:227)
        at net.imglib2.interpolation.randomaccess.NLinearInterpolator.graycodeFwdRecursive(NLinearInterpolator.java:233)
        at net.imglib2.interpolation.randomaccess.NLinearInterpolator.graycodeFwdRecursive(NLinearInterpolator.java:233)
        at net.imglib2.interpolation.randomaccess.NLinearInterpolator.graycodeFwdRecursive(NLinearInterpolator.java:233)
        at net.imglib2.interpolation.randomaccess.NLinearInterpolator.get(NLinearInterpolator.java:205)
        at net.imglib2.interpolation.randomaccess.NLinearInterpolator.get(NLinearInterpolator.java:53)
        at net.imglib2.realtransform.RealTransformRealRandomAccessible$RealTransformRealRandomAccess.get(RealTransformRealRandomAccessible.java:97)
        at net.imglib2.realtransform.DeformationFieldTransform.apply(DeformationFieldTransform.java:124)
        at net.imglib2.realtransform.AbstractRealTransformSequence.apply(AbstractRealTransformSequence.java:156)
        at net.imglib2.realtransform.ExplicitInvertibleRealTransform.apply(ExplicitInvertibleRealTransform.java:68)
        at net.imglib2.realtransform.AbstractRealTransformSequence.apply(AbstractRealTransformSequence.java:163)
        at net.imglib2.realtransform.AbstractRealTransformSequence.apply(AbstractRealTransformSequence.java:160)
        at net.imglib2.realtransform.RealTransformRealRandomAccessible$RealTransformRealRandomAccess.apply(RealTransformRealRandomAccessible.java:90)
        at net.imglib2.realtransform.RealTransformRealRandomAccessible$RealTransformRealRandomAccess.get(RealTransformRealRandomAccessible.java:96)
        at net.imglib2.view.RandomAccessibleOnRealRandomAccessible$RandomAccessOnRealRandomAccessible.get(RandomAccessibleOnRealRandomAccessible.java:194)
        at util.RenderUtil$2.call(RenderUtil.java:226)
        at util.RenderUtil$2.call(RenderUtil.java:213)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: Index 15360 out of bounds for length 15360
        at net.imglib2.cache.ref.SoftRefLoaderCache.get(SoftRefLoaderCache.java:111)
        at net.imglib2.cache.util.LoaderCacheAsCacheAdapter.get(LoaderCacheAsCacheAdapter.java:30)
        at net.imglib2.cache.util.CacheAsUncheckedCacheAdapter.get(CacheAsUncheckedCacheAdapter.java:28)
        ... 29 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 15360 out of bounds for length 15360
        at net.imglib2.img.basictypeaccess.array.AbstractShortArray.getValue(AbstractShortArray.java:61)
        at net.imglib2.type.numeric.integer.GenericShortType.getShort(GenericShortType.java:131)
        at net.imglib2.type.numeric.integer.GenericShortType.set(GenericShortType.java:187)
        at net.imglib2.type.numeric.integer.GenericShortType.set(GenericShortType.java:53)
        at org.janelia.saalfeldlab.n5.imglib2.N5CellLoader.copyIntersection(N5CellLoader.java:328)
        at org.janelia.saalfeldlab.n5.imglib2.N5CellLoader.lambda$createCopy$2(N5CellLoader.java:205)
        at org.janelia.saalfeldlab.n5.imglib2.N5CellLoader.load(N5CellLoader.java:144)
        at net.imglib2.cache.img.LoadedCellCacheLoader.get(LoadedCellCacheLoader.java:91)
        at net.imglib2.cache.img.LoadedCellCacheLoader.get(LoadedCellCacheLoader.java:51)
        at net.imglib2.cache.ref.SoftRefLoaderCache.get(SoftRefLoaderCache.java:101)
        ... 31 more
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: Index 15360 out of bounds for length 15360
        at net.imglib2.cache.util.CacheAsUncheckedCacheAdapter.get(CacheAsUncheckedCacheAdapter.java:32)
        at net.imglib2.img.cell.LazyCellImg$LazyCells.get(LazyCellImg.java:104)
        at net.imglib2.img.list.AbstractLongListImg$LongListRandomAccess.get(AbstractLongListImg.java:274)
        at net.imglib2.img.cell.CellRandomAccess.getCell(CellRandomAccess.java:136)
        at net.imglib2.img.cell.CellRandomAccess.updatePosition(CellRandomAccess.java:474)
        at net.imglib2.img.cell.CellRandomAccess.fwd(CellRandomAccess.java:164)
        at net.imglib2.view.FullSourceMapSlicingRandomAccess.fwd(FullSourceMapSlicingRandomAccess.java:183)
        at net.imglib2.converter.AbstractConvertedRandomAccess.fwd(AbstractConvertedRandomAccess.java:110)
        at net.imglib2.outofbounds.AbstractOutOfBoundsValue.fwd(AbstractOutOfBoundsValue.java:138)
        at net.imglib2.interpolation.randomaccess.NLinearInterpolator.graycodeFwdRecursive(NLinearInterpolator.java:227)
        at net.imglib2.interpolation.randomaccess.NLinearInterpolator.graycodeFwdRecursive(NLinearInterpolator.java:233)
        at net.imglib2.interpolation.randomaccess.NLinearInterpolator.graycodeFwdRecursive(NLinearInterpolator.java:233)
        at net.imglib2.interpolation.randomaccess.NLinearInterpolator.graycodeFwdRecursive(NLinearInterpolator.java:233)
        at net.imglib2.interpolation.randomaccess.NLinearInterpolator.get(NLinearInterpolator.java:205)
        at net.imglib2.interpolation.randomaccess.NLinearInterpolator.get(NLinearInterpolator.java:53)
        at net.imglib2.realtransform.RealTransformRealRandomAccessible$RealTransformRealRandomAccess.get(RealTransformRealRandomAccessible.java:97)
        at net.imglib2.realtransform.DeformationFieldTransform.apply(DeformationFieldTransform.java:124)
        at net.imglib2.realtransform.AbstractRealTransformSequence.apply(AbstractRealTransformSequence.java:156)
        at net.imglib2.realtransform.ExplicitInvertibleRealTransform.apply(ExplicitInvertibleRealTransform.java:68)
        at net.imglib2.realtransform.AbstractRealTransformSequence.apply(AbstractRealTransformSequence.java:163)
        at net.imglib2.realtransform.AbstractRealTransformSequence.apply(AbstractRealTransformSequence.java:160)
        at net.imglib2.realtransform.RealTransformRealRandomAccessible$RealTransformRealRandomAccess.apply(RealTransformRealRandomAccessible.java:90)
        at net.imglib2.realtransform.RealTransformRealRandomAccessible$RealTransformRealRandomAccess.get(RealTransformRealRandomAccessible.java:96)
        at net.imglib2.view.RandomAccessibleOnRealRandomAccessible$RandomAccessOnRealRandomAccessible.get(RandomAccessibleOnRealRandomAccessible.java:194)
        at util.RenderUtil$2.call(RenderUtil.java:226)
        at util.RenderUtil$2.call(RenderUtil.java:213)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: Index 15360 out of bounds for length 15360
        at net.imglib2.cache.ref.SoftRefLoaderCache.get(SoftRefLoaderCache.java:111)
        at net.imglib2.cache.util.LoaderCacheAsCacheAdapter.get(LoaderCacheAsCacheAdapter.java:30)
        at net.imglib2.cache.util.CacheAsUncheckedCacheAdapter.get(CacheAsUncheckedCacheAdapter.java:28)
        ... 29 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 15360 out of bounds for length 15360
        at net.imglib2.img.basictypeaccess.array.AbstractShortArray.getValue(AbstractShortArray.java:61)
        at net.imglib2.type.numeric.integer.GenericShortType.getShort(GenericShortType.java:131)
        at net.imglib2.type.numeric.integer.GenericShortType.set(GenericShortType.java:187)
        at net.imglib2.type.numeric.integer.GenericShortType.set(GenericShortType.java:53)
        at org.janelia.saalfeldlab.n5.imglib2.N5CellLoader.copyIntersection(N5CellLoader.java:328)
        at org.janelia.saalfeldlab.n5.imglib2.N5CellLoader.lambda$createCopy$2(N5CellLoader.java:205)
        at org.janelia.saalfeldlab.n5.imglib2.N5CellLoader.load(N5CellLoader.java:144)
        at net.imglib2.cache.img.LoadedCellCacheLoader.get(LoadedCellCacheLoader.java:91)
        at net.imglib2.cache.img.LoadedCellCacheLoader.get(LoadedCellCacheLoader.java:51)
        at net.imglib2.cache.ref.SoftRefLoaderCache.get(SoftRefLoaderCache.java:101)
        ... 31 more
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: Index 15360 out of bounds for length 15360
        at net.imglib2.cache.util.CacheAsUncheckedCacheAdapter.get(CacheAsUncheckedCacheAdapter.java:32)
        at net.imglib2.img.cell.LazyCellImg$LazyCells.get(LazyCellImg.java:104)
        at net.imglib2.img.list.AbstractLongListImg$LongListRandomAccess.get(AbstractLongListImg.java:274)
        at net.imglib2.img.cell.CellRandomAccess.getCell(CellRandomAccess.java:136)
        at net.imglib2.img.cell.CellRandomAccess.updatePosition(CellRandomAccess.java:474)
        at net.imglib2.img.cell.CellRandomAccess.fwd(CellRandomAccess.java:164)
        at net.imglib2.view.FullSourceMapSlicingRandomAccess.fwd(FullSourceMapSlicingRandomAccess.java:183)
        at net.imglib2.converter.AbstractConvertedRandomAccess.fwd(AbstractConvertedRandomAccess.java:110)
        at net.imglib2.outofbounds.AbstractOutOfBoundsValue.fwd(AbstractOutOfBoundsValue.java:138)
        at net.imglib2.interpolation.randomaccess.NLinearInterpolator.graycodeFwdRecursive(NLinearInterpolator.java:227)
        at net.imglib2.interpolation.randomaccess.NLinearInterpolator.graycodeFwdRecursive(NLinearInterpolator.java:233)
        at net.imglib2.interpolation.randomaccess.NLinearInterpolator.graycodeFwdRecursive(NLinearInterpolator.java:233)
        at net.imglib2.interpolation.randomaccess.NLinearInterpolator.graycodeFwdRecursive(NLinearInterpolator.java:233)
        at net.imglib2.interpolation.randomaccess.NLinearInterpolator.get(NLinearInterpolator.java:205)
        at net.imglib2.interpolation.randomaccess.NLinearInterpolator.get(NLinearInterpolator.java:53)
        at net.imglib2.realtransform.RealTransformRealRandomAccessible$RealTransformRealRandomAccess.get(RealTransformRealRandomAccessible.java:97)
        at net.imglib2.realtransform.DeformationFieldTransform.apply(DeformationFieldTransform.java:124)
        at net.imglib2.realtransform.AbstractRealTransformSequence.apply(AbstractRealTransformSequence.java:156)
        at net.imglib2.realtransform.ExplicitInvertibleRealTransform.apply(ExplicitInvertibleRealTransform.java:68)
        at net.imglib2.realtransform.AbstractRealTransformSequence.apply(AbstractRealTransformSequence.java:163)
        at net.imglib2.realtransform.AbstractRealTransformSequence.apply(AbstractRealTransformSequence.java:160)
        at net.imglib2.realtransform.RealTransformRealRandomAccessible$RealTransformRealRandomAccess.apply(RealTransformRealRandomAccessible.java:90)
        at net.imglib2.realtransform.RealTransformRealRandomAccessible$RealTransformRealRandomAccess.get(RealTransformRealRandomAccessible.java:96)
        at net.imglib2.view.RandomAccessibleOnRealRandomAccessible$RandomAccessOnRealRandomAccessible.get(RandomAccessibleOnRealRandomAccessible.java:194)
        at util.RenderUtil$2.call(RenderUtil.java:226)
        at util.RenderUtil$2.call(RenderUtil.java:213)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: Index 15360 out of bounds for length 15360
        at net.imglib2.cache.ref.SoftRefLoaderCache.get(SoftRefLoaderCache.java:111)
        at net.imglib2.cache.util.LoaderCacheAsCacheAdapter.get(LoaderCacheAsCacheAdapter.java:30)
        at net.imglib2.cache.util.CacheAsUncheckedCacheAdapter.get(CacheAsUncheckedCacheAdapter.java:28)
        ... 29 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 15360 out of bounds for length 15360
        at net.imglib2.img.basictypeaccess.array.AbstractShortArray.getValue(AbstractShortArray.java:61)
        at net.imglib2.type.numeric.integer.GenericShortType.getShort(GenericShortType.java:131)
        at net.imglib2.type.numeric.integer.GenericShortType.set(GenericShortType.java:187)
        at net.imglib2.type.numeric.integer.GenericShortType.set(GenericShortType.java:53)
        at org.janelia.saalfeldlab.n5.imglib2.N5CellLoader.copyIntersection(N5CellLoader.java:328)
        at org.janelia.saalfeldlab.n5.imglib2.N5CellLoader.lambda$createCopy$2(N5CellLoader.java:205)
        at org.janelia.saalfeldlab.n5.imglib2.N5CellLoader.load(N5CellLoader.java:144)
        at net.imglib2.cache.img.LoadedCellCacheLoader.get(LoadedCellCacheLoader.java:91)
        at net.imglib2.cache.img.LoadedCellCacheLoader.get(LoadedCellCacheLoader.java:51)
        at net.imglib2.cache.ref.SoftRefLoaderCache.get(SoftRefLoaderCache.java:101)
        ... 31 more
17:26:32.604 [main] INFO  process.TransformImage - writing to: fcwb-to-jrc18f.nrrd
Nrrd_Writer makeHeader
```

Can you help me debugging it ?
I am runnig this tool under Linux WSL (Ubuntu) on Windows 10.

**Comment by Nils-Reinhard** [comment]
Error does only appear in the WSL environment. 
Using a native Linux VM solved the issue for me.

**Comment by bogovicj** [comment]
thanks for the update @Nils-Reinhard
